modLoader = "javafml"
loaderVersion = "[36.2,)"
license = "MIT"

[[mods]] 
modId = "gigawhat_essentials" 
version = "0.2.0"
displayName = "Gigawhat Essentials (Beta)"
#logoFile = "examplemod.png"
authors = "Gigawhat Programing Team"
credits = "Samyar Sadat Akhavi, Hikmet Umut Bulut, Ekin Aksu"
description = '''
Gigawhat Essentials, a mod by Gigawhat.



§6§l§o------- Credits -------§r

§b§o---- Code ----§r
§7Lead developer : Samyar Sadat Akhavi
§7Developer : Ekin Aksu

§a§o---- Testing ----§r
§7Gigawhat Programing Team


§dCopyright © 2021 Gigawhat Programing Team.'''

[[dependencies.gigawhat_essentials]]

    modId = "forge"
    mandatory = true
    versionRange = "[36.2,)"
    ordering = "NONE"
    side = "SERVER"

[[dependencies.gigawhat_essentials]]

    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16, 1.16.5)"
    ordering = "NONE"
    side = "SERVER"
