blank_issues_enabled: false

contact_links:

  - name: Check past help requests
    url: https://github.com/Gigawhat-net/Gigawhat-Essentials/discussions/categories/q-a
    about: Visit the Q&A forum to search for previous help requests.

  - name: Check past feature suggestions
    url: 
    about: Visit the Feature Suggestions forum to view and discuss existing feature suggestions.

  - name: Create help request
    url: https://github.com/Gigawhat-net/Gigawhat-Essentials/discussions/new?category=q-a
    about: Create a support ticket to get help from developers.

  - name: Suggest a feature
    url: 
    about: Suggest new features for Gigawhat Essentials.

  - name: Get help on our Discord server
    url: https://discord.gg/rMq7GujUZJ
    about: Join the Gigawhat Discord server.
